### ISSUE TITLE
Log Spam With Custom Cloud configs.

### ISSUE THREAD

**Issue by LapisNator101** [LGhassen/EnvironmentalVisualEnhancements#1]
I'm having an issue with Log spam Coming From EVE in 1.10.1
It spams At the KSC, In flight, and whenever moving around in the tracking station.
It has happened to 2 different mods (Slippist and Komorfia)
The error is NullReferenceException: Object reference not set to an instance of an object
	CelestialShadows.LocalShadowComponent.OnPreCull () (at <3af23c21a34d4d36b0771138325c3afc>:0)
	UnityEngine.DebugLogHandler:LogException(Exception, Object)
	ModuleManager.UnityLogHandle.InterceptLogHandler:LogException(Exception, Object)
	UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
I've posted the log in a zip file if needed
[KSP.zip](https://github.com/LGhassen/EnvironmentalVisualEnhancements/files/5178560/KSP.zip)

**Comment by LGhassen** [comment]
Fixed in latest release
