### ISSUE TITLE
KSP 1.12 on macOS - No eve icon, BouldCo not detected

### ISSUE THREAD

**Issue by btgoodwin** [LGhassen/EnvironmentalVisualEnhancements#10]
I've been searching for what the missing trick is here but perhaps no one else is running this on macOS (Big Sur)?  I have KSP installed from Steam and I've unpacked `EnvironmentalVisualEnhancements`, `BoulderCo`, and `scatterer` as well as `ModuleManager4.2.1.dll` into my GameData folder, so it looks like this:

```
GameData
- BoulderCo/
- EnvironmentalVisualEnhancements/
- Scatterer/
- ModuleManager.4.2.1.dll
```

While the game is loading, I see the module manager indicate that it has loaded no patches.  This seems very strange because once in the game, the sidebar menu has 2 spaces for icons.  If I click one, I get Eve attempting to load its config (and failing, it says the config is not found for clouds, etc.).  If I click the other, I get a menu for scatterer, which appears to load properly.

I came from [this post](https://forum.kerbalspaceprogram.com/index.php?/topic/196411-19-112-eve-redux-performance-enhanced-eve-maintenance-v11131-18062021/) where there's a link to the releases page here (1.11.3.1) and the BoulderCo config (version 1.2.2.1).  Is there an extra step to getting this to work on macOS?

**Comment by LGhassen** [comment]
No extra steps, you have done it correctly. In redux I didn't modify any of the code about loading configs or anything like that, so it should still work the same.

Maybe something is wrong with your BoulderCo folder or something else, please include the log file.

**Comment by btgoodwin** [comment]
This was my screw-up.

I managed to nest a GameData folder in the GameData folder, and with the way Finder defaulted, it simply showed my _GameData_ as the window title and my files.  I stumbled across an ancient Reddit post about 30 minutes ago that said other contents in there should be Squad, SquadExpansion, etc. (since I have Breaking Ground and so forth), and yet mine contained none of those things.  I popped out to the parent directory and viola...I was setup wrong.  I just moved everything into the parent directory and now I have clouds, etc.  However, I also have some odd flickering on the horizon, graphical glitches.  I'm still investigating why.

For others reading this, I'm on an iMac 20,1 with a 5600XT, 4x FSAA, 4K resolution with all the vanilla graphics settings maxed (runs buttery smooth even with some rather large ships on screen).

I'm happy to close this issue as this was 100% just a goof-up on somehow getting a `GameData \ GameData \ <my mods>` going.

**Comment by btgoodwin** [comment]
I do wish I could find a few more examples of BoulderCo configs and what they ultimately "do" visually.  This stock one from the link seems to draw only clouds immediately nearby.  It's also missing an "atmosphere" section, it seems (according to the. config menu).  Are you aware of any place where configs + example screenshots are posted?

**Comment by LGhassen** [comment]
Sorry but I have no idea, check the EVE thread by wazwaz on the forum.

**Comment by btgoodwin** [comment]
Will do, thanks.  I'm experiencing some really awful-looking shadows and lighting from the surface of Minmus, for example.  Like one whole texture square where the ship is will be lit one crazy way, and then the adjacent squares will have some mishmash of shadows and light, over-saturation, etc. that make no sense, and so forth.

Thanks again for all your work on this, making it so performant!
