### ISSUE TITLE
Clouds not working in RSSVE with 1.11.4.1

### ISSUE THREAD

**Issue by siimav** [LGhassen/EnvironmentalVisualEnhancements#13]
Tested on KSP 1.10.1. Reverting back to 1.11.3.1 appears to fix the issue.
Let me know if there's anything you need to diagnose the issue.

**Comment by SpaceODY** [comment]
Same issue here with custom visuals for RSS.

**Comment by LGhassen** [comment]
Please include a log file so I can quickly check it for errors.

If it's possible also test it on 1.12, as I compiled the shaders with the newer version of unity associated with it. Didn't think it would be a problem.

**Comment by siimav** [comment]
Yes, on KSP 1.12 it appears to work correctly. I attached the log from KSP 1.10. Sorry for not pruning my install down to the minimum. :)
[KSP.zip](https://github.com/LGhassen/EnvironmentalVisualEnhancements/files/7486554/KSP.zip)

**Comment by LGhassen** [comment]
Thank you. A simple shader recompile with the older unity version should fix it then. However be advised that the next version of Scatterer will only work on 1.12 due to a new unity feature. Is there a major issue blocking RO/RSS from updating to 1.12 or it's just that no one has bothered to update/fix it?

**Comment by siimav** [comment]
1.12 just doesn't provide much interesting so I guess it's a lack of motivation. In addition to that, there's still a bunch of mods not managed by KSP-RO group that haven't gotten the 1.12 treatment.

**Comment by LGhassen** [comment]
Faire enough, I will push a recompiled version of EVE when I have time. Can't guarantee anything for the next Scatterer but I will keep it in mind.

**Comment by LGhassen** [comment]
Should be good now
