### ISSUE TITLE
Volumetric Clouds not appearing

### ISSUE THREAD

**Issue by retronexus** [LGhassen/EnvironmentalVisualEnhancements#14]
Hello! First, thanks for the great plugin continuation. 
I cannot get the volumetric clouds to appear like in your screenshots. Do i need another config file? or adjust settings?
I only get a very thin layer visible

**Comment by Gordon-Dry** [comment]
Perhaps you have a config with a patch like this inside a zFinal or similar folder inside GameData?
```
@EVE_CLOUDS:FINAL
{
	@OBJECT,*
	{
		!layerVolume{}
	}
}
```

**Comment by LGhassen** [comment]
> 
> 
> Hello! First, thanks for the great plugin continuation. I cannot get the volumetric clouds to appear like in your screenshots. Do i need another config file? or adjust settings? I only get a very thin layer visible

Can't really know if you don't give any info. Which configs are you using + log file

**Comment by LGhassen** [comment]
Closed due to no info
