### ISSUE TITLE
Blue Duna, Caused by EVE.

### ISSUE THREAD

**Issue by TJBotSN** [LGhassen/EnvironmentalVisualEnhancements#15]
Im almost positive that Duna being this blue, and Eve (the planet) having its Aurora glitched along with a weird cyan Z-fighting kind of thing has been caused by EVE, when i remove the mod, everything returns to normal (without Eve's benafites of course). Kerbin seems to be fine and working perfectly, but ive noticed on Laythe a weird Darkening around the planet that is very hard to notice at first glance but can be spotted.
Mod List:
![Capture](https://user-images.githubusercontent.com/96357437/147611871-e00ef311-108c-4760-b263-c904dbe632ce.PNG)
![20211228172847_1](https://user-images.githubusercontent.com/96357437/147611889-a337e01b-ea23-4193-9308-11f64f20d7c8.jpg)
![20211228172911_1](https://user-images.githubusercontent.com/96357437/147611895-912b2518-eafb-4efb-8589-441a01968041.jpg)
![20211228172927_1](https://user-images.githubusercontent.com/96357437/147611903-cf71e972-3bb6-4870-b655-6dc1fe281b0c.jpg)
![Inked20211228172857_1_LI](https://user-images.githubusercontent.com/96357437/147611912-9b60541f-1c6f-4040-9c74-a0a988b432b7.jpg)

Now i have no idea why these problems are caused, other than the fact they only arrise when EVE is present.

**Comment by TJBotSN** [comment]
I removed AVP from the folder and it seemed as if it was causing the issue, im guessing both overlay on Duna, im not sure how to solve that.

**Comment by LGhassen** [comment]
Closed this since it's a config issue
