### ISSUE TITLE
Neither Clouds Or Cities Showing in Stock with EVE

### ISSUE THREAD

**Issue by FishyFish01** [LGhassen/EnvironmentalVisualEnhancements#18]
Hi, as the title shows neither clouds or city lights are appearing in stock EVE. Attached below is my modlist. I can provide any additional needed information, just let me know. Thanks.

![image](https://user-images.githubusercontent.com/88445831/170890381-cf454ea3-d40b-42c4-b7d8-2cad916be595.png)

**Comment by FishyFish01** [comment]
Figured I should show the issue in image form too.

![image](https://user-images.githubusercontent.com/88445831/170890397-08b8779a-2179-4441-9f59-f75a3ece1235.png)

![image](https://user-images.githubusercontent.com/88445831/170890412-ad9df4f0-cc02-4164-bf52-1df44be57f4d.png)

**Comment by OpaqueArc** [comment]
Install via ckan and choose one of the recommended mods so that eve can receive config files, stock settings would make clouds work but not city lights, you would need AVP or something else that actually comes with city light configs for EVE to display it

**Comment by zhouyiqing0304** [comment]
i installed spectra
but it doesn't work

**Comment by LGhassen** [comment]
make a bug report with more info @zhouyiqing0304 

closing this because the original user didn't have a config installed.
