### ISSUE TITLE
Certain clouds don't render correctly in VR

### ISSUE THREAD

**Issue by JonnyOThan** [LGhassen/EnvironmentalVisualEnhancements#22]
https://github.com/JonnyOThan/Kerbal-VR/issues/119

Can you point me to the code that draws these? I'm currently poking around DeferredVolumetricCloudsRenderer - am I way off base?

The distant clouds you can see from the launchpad and from space work great, it's just these...fluffy...billboardy ones that don't.

**Comment by LGhassen** [comment]
Yeah it's those. They are rendered in two steps, off-screen render to low res texture and then upscale and copy to the screen.

**Comment by JonnyOThan** [comment]
Gotcha, thanks. I tried clearing the render target before drawing to the right eye and it fixed the doubling up problem but not the “clipping region” and the terrain etc was missing. I can probably figure out how to make sure the terrain works, but you’ll you mind explaining how the clouds decide where to not draw? Or rather does that come later when they are composited into the scene? Is it a stencil, depth buffer, etc?

**Comment by LGhassen** [comment]
Nicely done. So I guess you already understood how it works but the depth buffer is downscaled by picking the min value of 4 neighbours, and used to check for intersections, then for upscaling it compares the full res depth to the 4 nearest downscaled values and picks the color from the closest one.
