### ISSUE TITLE
Volumetric clouds do not work

### ISSUE THREAD

**Issue by Fluffy59** [LGhassen/EnvironmentalVisualEnhancements#28]
I have tried deleting mods, redownloading EVE installing a config file and nothing works

<img width="404" alt="image" src="https://user-images.githubusercontent.com/109255869/212753920-ce4fcf42-0bd6-4d16-ad66-24f3414f54da.png">

if more info is required tell me

**Comment by LGhassen** [comment]
If you mean the new clouds they aren't public yet, just a preview build on my Patreon.

**Comment by Fluffy59** [comment]
I feel stupid now... oh well i can wait
