### ISSUE TITLE
E.V.E and A.V.P. not working

### ISSUE THREAD

**Issue by Pluspython68** [LGhassen/EnvironmentalVisualEnhancements#35]
Astronomer's visual pack and Environmental Visual Enhancements aren't working, but occasionally, E.V.E. will work, but only the old clouds show, not the new volumetric ones.

[GameData screenshot](https://drive.google.com/file/d/1Mwl-Wz6SCF53Rn9hdZgVLTda6R8dfACE/view?usp=share_link)

[KSP.log](https://drive.google.com/file/d/1EqBc3Sl7La8lo59exwZtMPONmc3SDa4J/view?usp=share_link)

I've already got some support for this issue ([@Lisias](https://forum.kerbalspaceprogram.com/index.php?/profile/187168-lisias/)), and apparently, it's a problem with the EVEManager.

**Comment by LGhassen** [comment]
So the new volumetric clouds are only available on Patreon for now (sorry not allowed to talk about this on the forum so that's why information is sparse there).

Other than that it looks like something is wrong with your cubemap configs, it's throwing an error but I can't tell more.

**Comment by Pluspython68** [comment]
So how do I fix this?

**Comment by Pluspython68** [comment]
Do you need more information?

**Comment by Pluspython68** [comment]
Hello?

**Comment by LGhassen** [comment]
I don't know what's going on as I said, maybe try to narrow it down by removing mods or starting over

**Comment by Pluspython68** [comment]
I found the problem. AVP acts as its own config for EVE, and I still had boulderco installed!
