### ISSUE TITLE
Sun isn't shining

### ISSUE THREAD

**Issue by mussarela11** [LGhassen/EnvironmentalVisualEnhancements#38]
sun does not shine, like shown on the screenshot
![Captura de Tela (232)](https://github.com/LGhassen/EnvironmentalVisualEnhancements/assets/153830745/94dd4d2c-30f3-4d2a-aefd-7e44bfa88232)

**Comment by LGhassen** [comment]
Closing this because it's talking about sunflares which are unrelated to EVE
