### ISSUE TITLE
Terrain is rendering in weird way, when in atmosphere.

### ISSUE THREAD

**Issue by MandelbrotEnjoyer** [LGhassen/EnvironmentalVisualEnhancements#41]
Not really sure why it's happening, maybe fault of Scatter or EVE but just putting it out here. Only terrain from "RSS CanaveralHD" is rendered properly when in atmosphere.

KSP 1.10.1.2939

![KSP_BUG_REPORT](https://github.com/LGhassen/EnvironmentalVisualEnhancements/assets/144078648/b05e20cd-22c7-4a1c-92fa-79a17a26a394)
[Mod_List_For_Bug_Report.txt](https://github.com/user-attachments/files/16031859/Mod_List_For_Bug_Report.txt)

**Comment by LGhassen** [comment]
I would say you should report this to the maintainer of "RSS CanaveralHD"

**Comment by MandelbrotEnjoyer** [comment]
@LGhassen Already done that, He closed issue saying that problem is somewhere else as Canaveral does seem to be rendered properly

**Comment by LGhassen** [comment]
Then maybe to RSS maintainers, in any case this isn't an issue for me as it doesn't seem to be related to clouds or atmosphere. Seems like a config/texture issue.

**Comment by LGhassen** [comment]
Try to narrow it down, remove mods until you find the culprit or cause, otherwise we can't help you.

**Comment by LGhassen** [comment]
Closing this because it seems unrelated.

**Comment by MandelbrotEnjoyer** [comment]
Turned out it was caused by Parallax mod, after uninstalling it everything is fine
