### ISSUE TITLE
Is the nulref spam with kopernicus fixed ?

### ISSUE THREAD

**Issue by YT-GameWorks** [LGhassen/EnvironmentalVisualEnhancements#5]
Okay, this is not really an issue but a question: the nullref spam that occurred before with kopernicus, is it fixed ?

**Comment by LGhassen** [comment]
I think so but do you really need to open an issue to ask a question? You could have just tested it ingame

**Comment by YT-GameWorks** [comment]
I know but my computer is kinda slow and takes a long time to do stuff so I figured asking here would be faster,thanks anyway!

**Comment by LGhassen** [comment]
> I know but my computer is kinda slow and takes a long time to do stuff so I figured asking here would be faster,thanks anyway!

I think I fixed it but I don't know if we are talking about the same issue or not, there could be multiple
